version: '3'
services:
  web:
    image: ubuntu/apache2
    restart: unless-stopped
# Change ports when in use
    ports:
      - '8383:80'
      - '881:3306'
      - '8443:443'
    expose:
      - 8383
      - 881
      - 8443
    build: .
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "avideo"
      DB_MYSQL_PASSWORD: "root"
      DB_MYSQL_NAME: "avideo"
    volumes:
      - ./var/www/avideo:/var/www/avideo
    networks:
      - app_net
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - 8306:3306
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
